# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.colKurtCpp <- function(x) {
    .Call(`_nboot_colKurt`, x)
}

.rowKurtCpp <- function(x) {
    .Call(`_nboot_rowKurt`, x)
}

.betaBootNp <- function(y, X, nboot) {
    .Call(`_nboot_betaBoot`, y, X, nboot)
}

.betaBootWild <- function(y, X, nboot) {
    .Call(`_nboot_betaBootWild`, y, X, nboot)
}

.uExactBootNp <- function(x, y, nboot) {
    .Call(`_nboot_u_exact_boot_np`, x, y, nboot)
}

.uExactBootPerm <- function(x, y, nboot) {
    .Call(`_nboot_u_exact_boot_perm`, x, y, nboot)
}

.colMinCpp <- function(x) {
    .Call(`_nboot_colMin`, x)
}

.colMaxCpp <- function(x) {
    .Call(`_nboot_colMax`, x)
}

.rowMinCpp <- function(x) {
    .Call(`_nboot_rowMin`, x)
}

.rowMaxCpp <- function(x) {
    .Call(`_nboot_rowMax`, x)
}

.rowQuantCpp <- function(a, probs) {
    .Call(`_nboot_rowQuant`, a, probs)
}

.colQuantCpp <- function(a, probs) {
    .Call(`_nboot_colQuant`, a, probs)
}

.ColRankAvg <- function(x) {
    .Call(`_nboot_rankMatCol`, x)
}

.RowRankAvg <- function(x) {
    .Call(`_nboot_rankMatRow`, x)
}

.colSkewCpp <- function(x) {
    .Call(`_nboot_colSkew`, x)
}

.rowSkewCpp <- function(x) {
    .Call(`_nboot_rowSkew`, x)
}

