# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes sample excess kurtosis for each column of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample excess kurtosis for all columns
colKurt <- function(x) {
    .Call(`_nboot_colKurt`, x)
}

#' Computes sample excess kurtosis for each row of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample excess kurtosis for all rows
rowKurt <- function(x) {
    .Call(`_nboot_rowKurt`, x)
}

#' Computes columnwise minimum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of minimum value of each column
colMin <- function(x) {
    .Call(`_nboot_colMin`, x)
}

#' Computes columnwise maximum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of maximum value of each column
colMax <- function(x) {
    .Call(`_nboot_colMax`, x)
}

#' Computes rowwise minimum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of minimum value of each row
rowMin <- function(x) {
    .Call(`_nboot_rowMin`, x)
}

#' Computes rowwise maximum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of maximum value of each row
rowMax <- function(x) {
    .Call(`_nboot_rowMax`, x)
}

#' Computes rowwise quantiles of a numeric matrix
#'
#' @param x Numeric Matrix
#' @param probs Vector of quantiles to compute
#' @return Vector/Matrix of rowwise quantiles
rowQuant <- function(a, probs) {
    .Call(`_nboot_rowQuant`, a, probs)
}

#' Computes columnwise quantiles of a numeric matrix
#'
#' @param x Numeric Matrix
#' @param probs Vector of quantiles to compute
#' @return Vector/Matrix of columnwise quantiles
colQuant <- function(a, probs) {
    .Call(`_nboot_colQuant`, a, probs)
}

#' Computes sample skewness for each column of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample skewness for all columns
colSkew <- function(x) {
    .Call(`_nboot_colSkew`, x)
}

#' Computes sample skewness for each row of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample skewness for all rows
rowSkew <- function(x) {
    .Call(`_nboot_rowSkew`, x)
}

