# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes sample excess kurtosis for each column of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample excess kurtosis for all columns
.colKurtCpp <- function(x) {
    .Call(`_nboot_colKurt`, x)
}

#' Computes sample excess kurtosis for each row of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample excess kurtosis for all rows
.rowKurtCpp <- function(x) {
    .Call(`_nboot_rowKurt`, x)
}

.betaBootNp <- function(y, X, nboot) {
    .Call(`_nboot_betaBoot`, y, X, nboot)
}

#' Computes columnwise minimum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of minimum value of each column
.colMinCpp <- function(x) {
    .Call(`_nboot_colMin`, x)
}

#' Computes columnwise maximum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of maximum value of each column
.colMaxCpp <- function(x) {
    .Call(`_nboot_colMax`, x)
}

#' Computes rowwise minimum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of minimum value of each row
.rowMinCpp <- function(x) {
    .Call(`_nboot_rowMin`, x)
}

#' Computes rowwise maximum of a numeric matrix
#'
#' @param x Numeric Matrix
#' @return Vector of maximum value of each row
.rowMaxCpp <- function(x) {
    .Call(`_nboot_rowMax`, x)
}

#' Computes rowwise quantiles of a numeric matrix
#'
#' @param x Numeric Matrix
#' @param probs Vector of quantiles to compute
#' @return Vector/Matrix of rowwise quantiles
.rowQuantCpp <- function(a, probs) {
    .Call(`_nboot_rowQuant`, a, probs)
}

#' Computes columnwise quantiles of a numeric matrix
#'
#' @param x Numeric Matrix
#' @param probs Vector of quantiles to compute
#' @return Vector/Matrix of columnwise quantiles
.colQuantCpp <- function(a, probs) {
    .Call(`_nboot_colQuant`, a, probs)
}

#' Computes sample skewness for each column of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample skewness for all columns
.colSkewCpp <- function(x) {
    .Call(`_nboot_colSkew`, x)
}

#' Computes sample skewness for each row of a matrix
#'
#' @param x Numeric Matrix
#' @return Vector of sample skewness for all rows
.rowSkewCpp <- function(x) {
    .Call(`_nboot_rowSkew`, x)
}

